### ISSUE TITLE
Publish the bloXroute relay source code

### ISSUE THREAD

**Issue by metachris** [bloXroute-Labs/mev-relay#2]
Hey guys,

The bloXroute relay is based on https://github.com/flashbots/mev-boost-relay, which is AGPL licensed. This means that all changes to mev-relay must be public, which basically means to work in the open generally.

Currently the code of this mev-relay repository is 5 months old, way before Shapella.

Time to publish your current code, guys. And please keep your relay codebase open going forward!

Thanks 🙌

**Comment by benhenryhunter** [comment]
Thanks for bringing this to our attention 🙏 

This is resolved with #3
