### ISSUE TITLE
Please comply with the mev-boost-relay AGPL license

### ISSUE THREAD

**Issue by metachris** [bloXroute-Labs/mev-relay#5]
As [pointed out previously](https://github.com/bloXroute-Labs/mev-relay/issues/2), at Flashbots we are happy that you build on top of our mev-boost-relay codebase.

Our [codebase is AGPL licensed](https://github.com/flashbots/mev-boost-relay), which requires all modifications to be made public.

Sadly, it seems Bloxroute is again working primarily in private repositories, without having the code of your fork public by default, as mandated by the AGPL license.

We ask that you comply with the mev-boost-relay license by working in the open continuously publish your latest code here, instead of irregular dumps when we ask for it.

Happy to help if you have any questions or concerns, please just reach out.

**Comment by benhenryhunter** [comment]
We haven't made any changes in the last 3 weeks.  We've been focused primarily on our builder and have been modifying some redis params on startups.  I had a local change that I used for a test release saving payloads ahead of our `handleBlockPayload` method but we never moved forward with it so I never pushed it 🤷 

Today I'm working on implementing https://github.com/flashbots/mev-boost-relay/pull/446 so you'll see that in a few.

**Comment by metachris** [comment]
Great to hear, thanks for the update ⭐
